name: Create Pull Request on merge in Deploy branch

on:
  push:
    branches:
      - deploy
      - main

    

jobs: 
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: print pr title
        run: echo ${{ github.event.pull_request.title }}

      


    