name: Create Pull Request on merge in Deploy branch

on:
  pull_request:
    types:
      - closed
    branches: 
      - deploy
      - main

jobs:
  create_pull_request:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: echo pr title
        run: echo ${{ github.event.pull_request.title}}






      


    