name: Create Pull Request on merge in Deploy branch

on:
  push:
    branches:
      - deploy
      - main

    

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
    